module.exports = [
  "3d printer",
  "3d printing",
  "404",
  "abandonware",
  "accelerator board",
  "access provider",
  "access time",
  "activity tracker",
  "ada",
  "ad blocker",
  "ad blocking",
  "adder",
  "add-in",
  "additive manufacturing",
  "add-on",
  "address bar",
  "address book",
  "adware",
  "aggregator",
  "air gap",
  "algol",
  "algorithmic trading",
  "algo trading",
  "alpha geek",
  "alphanumeric",
  "alpha test",
  "alpha version",
  "alt key",
  "analogue",
  "analytics",
  "anonymous ftp",
  "api",
  "app",
  "applet",
  "application programming interface",
  "arithmetic logic unit",
  "artificial intelligence",
  "artificial life",
  "asp",
  "assembly language",
  "at",
  "attachment",
  "audio",
  "augmented reality",
  "authentication",
  "authoring",
  "autocomplete",
  "autocorrect",
  "autofill",
  "automation",
  "autoplay",
  "autoresponder",
  "autosave",
  "back button",
  "backing store",
  "backlink",
  "backplane",
  "backslash",
  "backspace",
  "badware",
  "basic",
  "basket",
  "batch file",
  "batch processing",
  "baud",
  "benchmark",
  "benchmark test",
  "bench test",
  "beta test",
  "beta version",
  "big data",
  "binary code",
  "binary coded decimal",
  "binary system",
  "binary tree",
  "biocomputer",
  "biocomputing",
  "bios",
  "bit",
  "bitcoin",
  "bitmap",
  "bitnet",
  "bittorrent",
  "blackberry",
  "black hat",
  "bloatware",
  "blockchain",
  "block diagram",
  "blog",
  "blogger",
  "blogosphere",
  "blog post",
  "blogroll",
  "bluetooth",
  "bookmark",
  "bookmarklet",
  "bootloader",
  "boss key",
  "bot",
  "botnet",
  "bounce rate",
  "break point",
  "brochureware",
  "brogrammer",
  "browse",
  "b-tree",
  "bubblejet printer",
  "bubble memory",
  "bug fix",
  "bulletin board",
  "burn-in",
  "byod",
  "byte",
  "cad",
  "calculator",
  "cam",
  "cancelbot",
  "captcha",
  "cd-r",
  "cd-rom",
  "cd-rw",
  "cellular automaton",
  "central processing unit",
  "cgi",
  "chad",
  "changer",
  "character code",
  "character recognition",
  "character string",
  "chat",
  "chatbot",
  "chat room",
  "chatterbot",
  "checkbox",
  "checker",
  "checksum",
  "clean room",
  "clickbait",
  "click fraud",
  "clickjacking",
  "click rate",
  "clicks and mortar",
  "clickstream",
  "click-through",
  "clip art",
  "clipboard",
  "clock speed",
  "cloud computing",
  "cobol",
  "codec",
  "combo box",
  "command language",
  "command line",
  "comments section",
  "compact disc",
  "compression",
  "computer",
  "computer conferencing",
  "computer dating",
  "computer game",
  "computer model",
  "computer programmer",
  "computer science",
  "computing",
  "concatenation",
  "condition code",
  "configuration",
  "connectionism",
  "connectivity",
  "console",
  "consumer electronics",
  "content farm",
  "content provider",
  "continuous stationery",
  "control character",
  "control key",
  "conventional memory",
  "coprocessor",
  "copyleft",
  "core dump",
  "courseware",
  "crimeware",
  "cron",
  "cross-assembler",
  "cross-compiler",
  "cross-posting",
  "cruft",
  "cursor",
  "cut and paste",
  "cutscene",
  "cyberattack",
  "cyberbullying",
  "cybercafe",
  "cybercast",
  "cyberchondriac",
  "cybercrime",
  "cybercrook",
  "cyberculture",
  "cybernaut",
  "cyberphobia",
  "cybersecurity",
  "cybersex",
  "cyberslacker",
  "cyberspace",
  "cybersphere",
  "cybersquatting",
  "cyberstalking",
  "cyberterrorism",
  "cybertheft",
  "cyberthreat",
  "cyberwar",
  "cyberwarfare",
  "cyberwarrior",
  "cyclic redundancy check",
  "cypherpunk",
  "daemon",
  "daisy wheel",
  "darknet",
  "dark web",
  "data",
  "databank",
  "database",
  "database management system",
  "data capture",
  "data centre",
  "data dictionary",
  "data dump",
  "dataglove",
  "data link",
  "data mining",
  "data processing",
  "data protection",
  "data scientist",
  "data set",
  "data smog",
  "data terminal",
  "data type",
  "dataveillance",
  "data visualization",
  "data warehouse",
  "day trading",
  "dde",
  "ddos",
  "debug",
  "debugger",
  "decision support system",
  "deduplication",
  "deep web",
  "demo",
  "denial of service",
  "density",
  "desktop",
  "desktop publishing",
  "development system",
  "dialler",
  "dialog box",
  "dick pic",
  "dictionary attack",
  "digerati",
  "digital divide",
  "digital footprint",
  "digital frame",
  "digital immigrant",
  "digital native",
  "digital signature",
  "digital watermark",
  "digital watermarking",
  "digitization",
  "dip",
  "dip switch",
  "direct access",
  "disassembler",
  "disc",
  "discoverability",
  "discussion board",
  "disk drive",
  "display",
  "distributed denial of service",
  "distro",
  "dm",
  "docking station",
  "documentation",
  "domain name",
  "dongle",
  "dos",
  "dot-com",
  "dot-commer",
  "dot matrix",
  "dot-org",
  "double precision",
  "download",
  "downtime",
  "downvote",
  "drive bay",
  "dumbphone",
  "dvd",
  "dvd-r",
  "dvd-rom",
  "dvd-rw",
  "e-banking",
  "e-billing",
  "e-book",
  "e-card",
  "e-cash",
  "e-commerce",
  "e-content",
  "e-crime",
  "e-dating",
  "edit suite",
  "e-edition",
  "e-fit",
  "e-ink",
  "electronic organizer",
  "electronic signature",
  "email",
  "emoji",
  "emoticon",
  "emulation",
  "encapsulation",
  "encryption",
  "end user",
  "eprom",
  "erasure",
  "e-reader",
  "error correction",
  "error message",
  "e-security",
  "e-signature",
  "e-sport",
  "e-tailer",
  "ethernet",
  "ethical hacker",
  "exabyte",
  "exclusive or",
  "executable",
  "expansion card",
  "expansion slot",
  "expert system",
  "extranet",
  "eyedropper",
  "e-zine",
  "failover",
  "false colour",
  "faq",
  "fat finger",
  "favicon",
  "feature phone",
  "file extension",
  "file manager",
  "filename",
  "file server",
  "file-sharing",
  "firewire",
  "firmware",
  "fitness tracker",
  "flame war",
  "flash drive",
  "flash memory",
  "flat file",
  "flat screen",
  "flic",
  "flip chip",
  "floating-point",
  "floppy drive",
  "floptical",
  "flow chart",
  "fly-through",
  "folder",
  "folksonomy",
  "followee",
  "force feedback",
  "fortran",
  "forum",
  "forumite",
  "forward slash",
  "fragmentation",
  "freemium",
  "freeware",
  "function key",
  "gamepad",
  "gameplay",
  "gamer",
  "gamification",
  "garbage collection",
  "gate array",
  "geekspeak",
  "generator",
  "geodata",
  "geofence",
  "geofencing",
  "geoinformation",
  "geolocation",
  "geomatics",
  "geotag",
  "ghost site",
  "gif",
  "gig",
  "gigabit",
  "gigabyte",
  "gigaflop",
  "gigahertz",
  "gigapixel",
  "global village",
  "gold farming",
  "google bomb",
  "googlewhack",
  "grammar checker",
  "graphicacy",
  "graphical display",
  "graphical user interface",
  "graphics accelerator",
  "graphics card",
  "graphics tablet",
  "greyscale",
  "griefer",
  "groupware",
  "guestbook",
  "hackathon",
  "hacker",
  "hackerspace",
  "hacktivist",
  "half-move",
  "handheld device",
  "handshake",
  "handshaking",
  "hard copy",
  "hard disk",
  "hard drive",
  "hard error",
  "hashtag",
  "help desk",
  "help key",
  "high definition",
  "home computer",
  "home page",
  "home screen",
  "hot key",
  "hotlink",
  "hotlist",
  "html",
  "hyperinstrument",
  "hyperlink",
  "hypermedia",
  "hypertext",
  "ide",
  "identifier",
  "im",
  "image macro",
  "image processing",
  "imagesetter",
  "i-mode",
  "inbox",
  "incremental backup",
  "infobahn",
  "infographic",
  "infomania",
  "infomediary",
  "informatics",
  "information processing",
  "information retrieval",
  "information retrieval system",
  "information science",
  "information scientist",
  "information technology",
  "information transfer",
  "inkjet printer",
  "input",
  "instant message",
  "instruction set",
  "integrated services digital network",
  "integrator",
  "interactive mode",
  "interactivity",
  "interlingua",
  "internaut",
  "internet",
  "internet appliance",
  "internet banking",
  "internet cafe",
  "internet of things",
  "internet protocol",
  "internet service provider",
  "internet site",
  "interoperability",
  "interweb",
  "intranet",
  "ios",
  "iot",
  "ip",
  "ip address",
  "ipod",
  "isp",
  "it",
  "iterate",
  "iteration",
  "java",
  "javascript",
  "job control language",
  "joypad",
  "jpeg",
  "jump instruction",
  "jumpstation",
  "junk email",
  "kern",
  "keyboard",
  "keyboard shortcut",
  "keylogger",
  "keylogging",
  "keypad",
  "keypal",
  "keypunch",
  "keystroke",
  "keyword",
  "killer app",
  "kill file",
  "kilobit",
  "kilobyte",
  "kludge",
  "knowbot",
  "knowledge base",
  "knowledge engineering",
  "knowledge worker",
  "kwic",
  "landing page",
  "lappy",
  "laptop",
  "laser printer",
  "least significant bit",
  "leet",
  "leetspeak",
  "lifecast",
  "light gun",
  "light pen",
  "like",
  "line printer",
  "linkbait",
  "linked list",
  "linker",
  "link farm",
  "link-up",
  "linux",
  "lisp",
  "list",
  "list box",
  "listicle",
  "list processing",
  "listserv",
  "live blog",
  "live-stream",
  "liveware",
  "local area network",
  "local bus",
  "lock screen",
  "logic bomb",
  "logic circuit",
  "login",
  "logout",
  "lolcat",
  "lookup",
  "ludology",
  "lunch box",
  "mac",
  "machine code",
  "machine instruction",
  "machine intelligence",
  "machine translation",
  "machinima",
  "macro",
  "mail merge",
  "mainframe",
  "main memory",
  "maintainer",
  "malvertisement",
  "malvertising",
  "malware",
  "man page",
  "m-commerce",
  "megabit",
  "megabyte",
  "megaflop",
  "megahertz",
  "megapixel",
  "memory bank",
  "memory board",
  "memory card",
  "memory chip",
  "memory leak",
  "memory mapping",
  "memory stick",
  "menu bar",
  "message",
  "message board",
  "message box",
  "message switching",
  "metadata",
  "metafile",
  "meta key",
  "metaverse",
  "micro",
  "microblog",
  "microblogging",
  "microbrowser",
  "microcode",
  "microcomputer",
  "microcontroller",
  "microinstruction",
  "microkernel",
  "micropayment",
  "microprocessor",
  "microprogram",
  "microsite",
  "middleware",
  "millennium bug",
  "minicomputer",
  "minitower",
  "mips",
  "mmo",
  "mmog",
  "mmorpg",
  "mo",
  "mobile communication",
  "mobile device",
  "mobile internet",
  "moblog",
  "mobo",
  "mocap",
  "modem",
  "monte carlo method",
  "mooc",
  "most significant bit",
  "motherboard",
  "motion capture",
  "mouseover",
  "mouse potato",
  "mp",
  "mp3",
  "mp3 player",
  "mpeg",
  "msm",
  "mud",
  "multicast",
  "multiplayer",
  "multiprocessor",
  "multithreading",
  "multitouch",
  "mung",
  "nagware",
  "namespace",
  "nand",
  "natural language processing",
  "nematic",
  "netbook",
  "nethead",
  "netiquette",
  "netizen",
  "net neutrality",
  "netroots",
  "network analysis",
  "network appliance",
  "networker",
  "network operator",
  "neural computer",
  "neural network",
  "newbie",
  "new media",
  "newsgroup",
  "newswire",
  "node",
  "non-resident",
  "non-solid colour",
  "noob",
  "normal form",
  "notebook",
  "notepad",
  "null character",
  "null link",
  "number cruncher",
  "numerical control",
  "object code",
  "object program",
  "occam",
  "ohnosecond",
  "online dating",
  "online gamer",
  "online gaming",
  "onliner",
  "opcode",
  "open system",
  "operating system",
  "operation code",
  "optical character recognition",
  "option card",
  "otaku",
  "outliner",
  "packet network",
  "packet sniffer",
  "packet switching",
  "page view",
  "palmtop",
  "pane",
  "paper jam",
  "paper tape",
  "parallel port",
  "parallel processing",
  "parameter",
  "parity bit",
  "parser",
  "pascal",
  "password",
  "patchboard",
  "patch panel",
  "pathname",
  "pay-per-click",
  "paywall",
  "pb",
  "pc card",
  "pci",
  "pda",
  "pdf",
  "peering",
  "perceptron",
  "perl",
  "permadeath",
  "permalink",
  "personal computer",
  "personal information manager",
  "personal organizer",
  "petabyte",
  "petaflop",
  "pgp",
  "phablet",
  "phishing",
  "phone hacking",
  "photoblog",
  "photo cd",
  "picture messaging",
  "pingback",
  "pixel",
  "pizza box",
  "plain text",
  "platform game",
  "plug and play",
  "plug-compatible",
  "plug-in",
  "podcast",
  "podcasting",
  "pointing device",
  "poke",
  "polish notation",
  "polynomial time",
  "port",
  "portability",
  "portable",
  "portable media player",
  "portal",
  "portlet",
  "posix",
  "posting",
  "postscript",
  "powerpoint",
  "power-up",
  "power user",
  "prefetch",
  "preload",
  "preprocessor",
  "pre-production",
  "printhead",
  "printout",
  "print preview",
  "print queue",
  "processor",
  "profiling",
  "programmer",
  "programming",
  "prolog",
  "pseudocode",
  "public key",
  "punched card",
  "punched tape",
  "push technology",
  "puter",
  "qr code",
  "quantum bit",
  "quantum computer",
  "qubit",
  "query language",
  "radio button",
  "raid",
  "ram",
  "random access",
  "ransomware",
  "raster image processor",
  "rdf",
  "read-in",
  "read-only memory",
  "read-out",
  "real time",
  "reboot",
  "recompile",
  "reflow",
  "refresh rate",
  "regex",
  "regular expression",
  "reinstall",
  "relational database",
  "render farm",
  "reserved word",
  "rip",
  "risc",
  "roll-in roll-out",
  "rom",
  "root directory",
  "rootkit",
  "router",
  "rss",
  "san",
  "scalability",
  "scareware",
  "scheduler",
  "scratch pad",
  "screencap",
  "screen dump",
  "screen grab",
  "screen saver",
  "screen scraping",
  "screenshot",
  "script kiddie",
  "scroll bar",
  "scroller",
  "scrolling",
  "sd card",
  "search engine",
  "search engine optimization",
  "search term",
  "second screen",
  "seek time",
  "selfie",
  "semantic web",
  "send",
  "seo",
  "sequential access",
  "serial port",
  "server farm",
  "service provider",
  "servlet",
  "shannon's theorem",
  "shareware",
  "sheet feeder",
  "shell program",
  "shift register",
  "shopping basket",
  "shopping cart",
  "shovelware",
  "shrink-wrap",
  "shutdown",
  "sig",
  "silicon chip",
  "silicon valley",
  "silver surfer",
  "sim",
  "simplex",
  "slacktivism",
  "slide show",
  "smartphone",
  "smart quotes",
  "smartwatch",
  "smiley face",
  "smo",
  "snackable",
  "snail mail",
  "snobol",
  "social gaming",
  "social graph",
  "social media",
  "social media optimization",
  "social networking",
  "social sharing",
  "social software",
  "soft copy",
  "soft key",
  "softphone",
  "software",
  "soho",
  "sound card",
  "soundex",
  "source code",
  "source program",
  "spam",
  "spam filter",
  "spammer",
  "sparkline",
  "spear phishing",
  "speech recognition",
  "spellcheck",
  "spellchecker",
  "spelling checker",
  "spin-down",
  "split screen",
  "spreadsheet",
  "spyware",
  "ssd",
  "static",
  "status bar",
  "steganography",
  "stereogram",
  "stereolithography",
  "stopword",
  "storage",
  "storage device",
  "subdirectory",
  "subdomain",
  "subfolder",
  "submenu",
  "subnetwork",
  "subprogram",
  "subroutine",
  "subscription",
  "subsystem",
  "supercomputer",
  "supercut",
  "superuser",
  "swapfile",
  "synthespian",
  "sysadmin",
  "sysop",
  "system operator",
  "systems analyst",
  "tabulator",
  "tag cloud",
  "talkboard",
  "tape streamer",
  "taskbar",
  "tcp",
  "tcp/ip",
  "teaching machine",
  "technical support",
  "technopreneur",
  "telecomputer",
  "teleconference",
  "teleconferencing",
  "telecottage",
  "telepresence",
  "telescreen",
  "teleshopping",
  "telesoftware",
  "teletex",
  "teletext",
  "teletypewriter",
  "telnet",
  "terabyte",
  "teraflop",
  "text editor",
  "text processing",
  "textspeak",
  "texture mapping",
  "text wrap",
  "throughput",
  "tick box",
  "tiff",
  "time slice",
  "timestamp",
  "title bar",
  "token ring",
  "toolbar",
  "toolbox",
  "toolset",
  "tooltip",
  "touchpad",
  "touchscreen",
  "trackback",
  "trackball",
  "trackpad",
  "translation table",
  "translator",
  "transputer",
  "trapdoor",
  "tree structure",
  "troll",
  "tts",
  "tuple",
  "turing machine",
  "turing test",
  "tweeps",
  "tweetup",
  "twitterati",
  "twittersphere",
  "twitterverse",
  "ui",
  "ultrabook",
  "ultraportable",
  "unicode",
  "unix",
  "upload",
  "uptime",
  "upvote",
  "url",
  "usb flash drive",
  "usenet",
  "user experience",
  "user interface",
  "user journey",
  "username",
  "utility program",
  "ux",
  "vapourware",
  "vdu",
  "vector processor",
  "video card",
  "videocast",
  "video chat",
  "videoconference",
  "videoconferencing",
  "video game",
  "videographics",
  "video mail",
  "viewdata",
  "viewgraph",
  "viewscreen",
  "virality",
  "viral marketing",
  "virtual memory",
  "virtual reality",
  "visual display unit",
  "vlog",
  "vodcast",
  "voice over internet protocol",
  "voice recognition",
  "voip",
  "vortal",
  "voxel",
  "wait state",
  "walk-through",
  "warez",
  "wavetable",
  "wav file",
  "web 2.0",
  "webcam",
  "webcast",
  "web chat",
  "webcomic",
  "web hosting",
  "webinar",
  "webisode",
  "weblink",
  "weblog",
  "webmail",
  "webmaster",
  "web page",
  "web ring",
  "website",
  "webspace",
  "webtoon",
  "webzine",
  "wetware",
  "whiteboard",
  "white hat",
  "wide area network",
  "wi-fi",
  "wiki",
  "wimp",
  "windowing",
  "windows",
  "winky face",
  "wireframe",
  "wire fraud",
  "word cloud",
  "word length",
  "word processing",
  "word processor",
  "word wrap",
  "workalike",
  "workaround",
  "work group",
  "working storage",
  "workstation",
  "world wide web",
  "worm",
  "xml",
  "yottabyte",
  "youtuber",
  "zettabyte",
  "zip file"
];
